added better error for when server not found.

diff --git a/mcwrapper b/mcwrapper
--- a/mcwrapper
+++ b/mcwrapper
@@ -517,7 +517,7 @@ function sanity_check {
   # check to make sure that things that need to exist exist.
   if [[ ! -e "$MINECRAFT_SERVER_PATH" ]]; then
     # the minecraft server path does not exist.
-    echo "Minecraft server not found! ($MINECRAFT_SERVER_PATH)" >&2
+    echo "Minecraft server not found! (MINECRAFT_SERVER_PATH=$MINECRAFT_SERVER_PATH)" >&2
     echo "" >&2
     exit $EXIT_MINECRAFT_SERVER_NOT_FOUND
   fi
