added better checks to detect a failure in downloading minecraft_server.jar

diff --git a/mcwrapper b/mcwrapper
--- a/mcwrapper
+++ b/mcwrapper
@@ -554,6 +554,13 @@ function download_minecraft_server () {
   # parse the download page and read the minecraft_server.jar download URI
   local MINECRAFT_SERVER_DOWNLOAD_URI=`curl --progress-bar "$MINECRAFT_SERVER_DOWNLOAD_PAGE" | grep -E -o 'href=".*?minecraft_server.jar.*"' | awk -F '"' '{ print $2; }'`
   
+  # check if there was an error grabbing the download page
+  if [[ "$?" != "0" || -z "$MINECRAFT_SERVER_DOWNLOAD_URI" ]]; then
+    echo "There was an error locating the download link. www.minecraft.net down?"
+    echo ""
+    exit $EXIT_DOWNLOAD_MINECRAFT_SERVER_FAILED
+  fi
+  
   # build the minecraft_server.jar download URL
   local MINECRAFT_SERVER_DOWNLOAD_URL="${MINECRAFT_SERVER_BASE_URL}/${MINECRAFT_SERVER_DOWNLOAD_URI}"
   
