working on integrating all of mcbackup into a mcwrapper with a backup action

diff --git a/mcwrapper b/mcwrapper
--- a/mcwrapper
+++ b/mcwrapper
@@ -10,6 +10,10 @@ MINECRAFT_SERVER_NAME="minecraft_server.jar"
 # filename of the minecraft server.properties file
 MINECRAFT_SERVER_PROPERTIES_NAME="server.properties"
 
+CURRENT_BACKUP_PATH="${BACKUP_DIRECTORY_PATH}/$CURRENT_BACKUP_NAME"
+LATEST_BACKUP_PATH="${BACKUP_DIRECTORY_PATH}/latest"
+
+
 # figure out where the config file lives
 function get_config_path {
 	
@@ -82,6 +86,23 @@ function default_config {
 
 	# the directory of the minecraft_server.jar based off $MINECRAFT_SERVER_PATH
 	MINECRAFT_SERVER_DIR_PATH=`dirname $MINECRAFT_SERVER_PATH`
+	
+	BACKUP_DIRECTORY_NAME="backups"
+	
+	# what the name of the symlink is.
+	LATEST_BACKUP_NAME="latest"
+	
+	# how many backups to keep in the backups directory
+	# (we automatically delete old backups)
+	# TODO: implement the following rules.
+	# set to -1 to retain ALL backups (never delete)
+	# set to 0 to completely disable backups.
+	BACKUPS_TO_KEEP=5
+	
+	# set backup name to
+	#   +%Y%m%d       -- just the datestamp; no time.
+	#   +%Y%m%d%H%M%S -- full timestamp including hour, minute, second
+	CURRENT_BACKUP_NAME=`date +%Y%m%d%H%M%S`
 }
 
 # run this to process a loaded config
@@ -115,6 +136,11 @@ function process_config {
 	# the path to the server.properties file
 	if [[ -z "$SERVER_PROPERTIES_PATH" ]]; then
 		SERVER_PROPERTIES_PATH=`dirname "$MINECRAFT_SERVER_PATH"`"/${MINECRAFT_SERVER_PROPERTIES_NAME}"
+	fi
+	
+	# BACKUP_DIRECTORY_PATH can be relative or absolute
+	if [[ -z "$BACKUP_DIRECTORY_PATH" ]]; then
+		BACKUP_DIRECTORY_PATH="${MINECRAFT_SERVER_DIR}/${BACKUP_DIRECTORY_NAME}"
 	fi
 }
 
@@ -208,6 +234,99 @@ function print_usage {
 	echo "Any other action is interpretted as a server command and is directed to the minecraft server"
 	echo ""
 }
+
+##########################################################################################
+## MCBackup portion: ============>>>>>>>>>>>>
+
+
+# create the backup directory
+function create_BACKUP_DIRECTORY_PATHectory () {
+	mkdir -p "$CURRENT_BACKUP_PATH"
+	
+	if [[ $? != 0 ]]; then
+		#an error occurred
+		echo "An error occurred when creating the backup directory."
+		exit 1
+	fi
+}
+
+# stop writing to the world file(s) after flushing the buffer
+function stop_writing_world () {
+	sh "$MCWRAPPER" save-all
+	sh "$MCWRAPPER" save-off
+}
+
+# begin writing the world data again
+function start_writing_world () {
+	sh "$MCWRAPPER" save-on
+}
+
+# copy the world data and configuration
+function do_backup () {
+	WORLD_DATA_DIR="${MINECRAFT_SERVER_DIR_PATH}/"`read_server_property level-name`
+	
+	cp -R "$WORLD_DATA_DIR" "$CURRENT_BACKUP_PATH/"
+	
+	if [[ $? != 0 ]]; then
+		#an error occurred
+		echo "An error occurred when copying the world data."
+		exit 1
+	fi
+	
+	cp -R "${MINECRAFT_SERVER_DIR_PATH}/"*.{txt,properties} "$CURRENT_BACKUP_PATH/"
+	
+	if [[ $? != 0 ]]; then
+		#an error occurred
+		echo "An error occurred when copying the configuration information"
+		exit 1
+	fi
+}
+
+function create_symlink () {
+	# then we symlink the current backup to "latest" in backups directory
+	if [[ -e "$LATEST_BACKUP_PATH" ]]; then
+		# if the symlink already exists, delete it before creating it.
+		rm "$LATEST_BACKUP_PATH"
+		
+		if [[ $? != 0 ]]; then
+			#an error occurred
+			echo "An error occurred when deleting the old symlink."
+			exit 1
+		fi
+	fi
+	ln -s "$CURRENT_BACKUP_PATH" "$LATEST_BACKUP_PATH"
+	
+	if [[ $? != 0 ]]; then
+		#an error occurred
+		echo "An error occurred when creating the symlink."
+		exit 1
+	fi
+}
+
+# delete old backups
+function cleanup_old_backups () {
+	OLD_BACKUPS=`ls -r "$BACKUP_DIRECTORY_PATH" | grep -v "$LATEST_BACKUP_NAME" | tail +"${BACKUPS_TO_KEEP}"`
+	for o in $OLD_BACKUPS; do
+		rm -rf "${BACKUP_DIRECTORY_PATH}/$o"
+		if [[ $? != 0 ]]; then
+			#an error occurred but don't exit.
+			echo "An error occurred when deleting a previous backup: $o."
+		fi
+	done
+}
+
+# does the actual backup
+function backup_world {
+	create_BACKUP_DIRECTORY_PATHectory
+	stop_writing_world
+	do_backup
+	start_writing_world
+	create_symlink
+	cleanup_old_backups
+}
+
+## End MCBackup portion.
+##########################################################################################
 
 ## begin meat of program:
 
