added more checks when running set_up_pipe

diff --git a/mcwrapper b/mcwrapper
--- a/mcwrapper
+++ b/mcwrapper
@@ -371,11 +371,21 @@ function check_is_running {
 
 function set_up_pipe {
 	if [[ ! -p "$COMMAND_PIPE" ]]; then
+	  # if the file exists, but it's not a pipe, then we can't start.
+	  if [[ -e "$COMMAND_PIPE" ]]; then
+	    echo "Cannot create the pipe ($COMMAND_PIPE)" >&2
+	    echo "A file or directory already exists." >&2
+	    echo ""
+	    exit "$EXIT_MAKE_FIFO_FAILED"
+	  fi
+	  
 		mkfifo "$COMMAND_PIPE"
 		
-		if [[ $? != 0 ]]; then
+		local PIPE_STATUS=$?
+		
+		if [[ $PIPE_STATUS != 0 ]]; then
 			# if mkfifo failed, print error message, exit non-zero.
-			echo "Error creating the pipe: $COMMAND_PIPE ($?)." >&2
+			echo "Error creating the pipe: $COMMAND_PIPE ($PIPE_STATUS)." >&2
 			exit $EXIT_MAKE_FIFO_FAILED
 		fi
 	fi
