refactored some if statements in send_command() function.

diff --git a/mcwrapper b/mcwrapper
--- a/mcwrapper
+++ b/mcwrapper
@@ -309,23 +309,13 @@ function read_command {
 }
 
 function send_command {
-	check_is_running
-	
-	if [[ $? != 0 ]]; then
-		echo "Server is NOT running. Not sending command" >&2
-		exit $SERVER_NOT_RUNNING
-	fi
+	check_is_running \
+	  || { echo "Server is NOT running. Not sending command" >&2; exit $SERVER_NOT_RUNNING }
 	
 	# echo the command into the command pipe to be picked up by the reader process:
 	COMMAND=$1
-	(echo "$COMMAND" > "$COMMAND_PIPE") &> /dev/null
-	
-	ERR=$?
-	# check if we were successful
-	if [[ $ERR != $EXIT_SUCCESS ]]; then
-	  echo "Error sending command: '${COMMAND}' (${ERR})" >&2
-	  exit $EXIT_SEND_COMMAND_FAILED
-	fi
+	{ (echo "$COMMAND" > "$COMMAND_PIPE") &> /dev/null } \
+	  || { echo "Error sending command: '${COMMAND}' (${?})" >&2; exit $EXIT_SEND_COMMAND_FAILED }
 }
 
 function create_pid {
