more work on installer

diff --git a/mcwrapper b/mcwrapper
--- a/mcwrapper
+++ b/mcwrapper
@@ -54,6 +54,10 @@ EXIT_LATEST_BACKUP_NOT_FOUND=56
 
 EXIT_BAD_COMPRESSION_TYPE=60
 
+# installer related codes:
+EXIT_CANNOT_BACKUP_OLD_MINECRAFT_SERVER=70
+
+# misc other codes:
 EXIT_RUNNING_AS_ROOT=99
 
 #### End Exit Codes
@@ -514,6 +518,8 @@ function run_installer () {
       echo ""
       exit $EXIT_SUCCESS
     fi
+    
+    backup_old_server
   fi
   
   echo -n "Is this where you wish to install the Minecraft Server? [Y/n]: "
@@ -525,14 +531,29 @@ function run_installer () {
     exit $EXIT_SUCCESS
   fi
   
-  echo "Installing..."
+  echo "Downloading and installing Minecraft Server..."
+  download_minecraft_server
   
   exit 0
 }
 
 # download the minecraft_server.jar file
+# parse the minecraft.net download page and look for the download link for the server
+# then download that to the necessary place
 function download_minecraft_server () {
-  return 0
+  local MINECRAFT_SERVER_DOWNLOAD_PAGE="http://www.minecraft.net/download.jsp"
+}
+
+# backs up an old minecraft_server.jar file before downloading a new one
+function backup_old_server () {
+  # back up the old minecraft server (just in case)
+  mv "$MINECRAFT_SERVER_PATH" "${MINECRAFT_SERVER_PATH}.old"
+  
+  if [[ $? != 0 ]]; then
+    echo "Failed backing up the old minecraft server!"
+    echo ""
+    exit $EXIT_CANNOT_BACKUP_OLD_MINECRAFT_SERVER
+  fi
 }
 
 ## End Installer portion.
