detect if curl is not installed and throw an appropriate error.

diff --git a/mcwrapper b/mcwrapper
--- a/mcwrapper
+++ b/mcwrapper
@@ -594,22 +594,25 @@ function run_installer () {
 function download_minecraft_server () {
   local MINECRAFT_SERVER_BASE_URL="http://www.minecraft.net"
   local MINECRAFT_SERVER_DOWNLOAD_PAGE="${MINECRAFT_SERVER_BASE_URL}/download"
-  
+
+  which curl \
+    || { echo "curl does not appear to be installed. This is required to download the Minecraft server" >&2; exit $EXIT_NO_CURL; }
+
   # parse the download page and read the minecraft_server.jar download URI
   local MINECRAFT_SERVER_DOWNLOAD_URI=`curl --progress-bar "$MINECRAFT_SERVER_DOWNLOAD_PAGE" | grep -E -o 'href="[^"]*?minecraft_server.jar.*"' | awk -F '"' '{ print $2; }'`
-  
+
   # check if there was an error grabbing the download page (either curl returns a bad value or we didn't find the URI)
   if [[ "$?" != "0" || -z "$MINECRAFT_SERVER_DOWNLOAD_URI" ]]; then
     echo "There was an error locating the download link. www.minecraft.net down?"
     echo ""
     exit $EXIT_DOWNLOAD_MINECRAFT_SERVER_FAILED
   fi
-  
+
   # build the minecraft_server.jar download URL
   local MINECRAFT_SERVER_DOWNLOAD_URL="${MINECRAFT_SERVER_DOWNLOAD_URI}"
-  
+
   local MINECRAFT_SERVER_TEMP_FILE="/tmp/minecraft_server.jar"
-  
+
   # if the tempfile exists, delete it
   if [[ -e "$MINECRAFT_SERVER_TEMP_FILE" ]]; then
     rm "$MINECRAFT_SERVER_TEMP_FILE"
