code cleanup.

diff --git a/libexec/mcwrapper b/libexec/mcwrapper
--- a/libexec/mcwrapper
+++ b/libexec/mcwrapper
@@ -427,7 +427,7 @@ function set_up_pipe {
     if [[ -e "$COMMAND_PIPE" ]]; then
       warn "Cannot create the pipe ($COMMAND_PIPE)"
       warn "A file or directory already exists."
-      echo ""
+      warn ""
       exit "$EXIT_MAKE_FIFO_FAILED"
     fi
 
@@ -497,7 +497,7 @@ function start_minecraft_in_foreground {
 function stop_minecraft {
   # if $BACKUP_ON_EXIT is non-zero length, then backup the world before exiting.
   if [[ ! -z "$BACKUP_ON_EXIT" ]]; then
-    echo ""
+    warn ""
     warn -n "Backing up world data before exiting..."
     ( backup_world )
     # TODO: check status of backup_world. Don't say "Done" if we didn't back anything up.
@@ -536,7 +536,7 @@ function check_server_log_exists {
   # make sure that the log file exists before trying to tail it.
   if [[ ! -e "$SERVER_LOG_PATH" ]]; then
     warn "Server log not found! ($SERVER_LOG_PATH)"
-    echo ""
+    warn ""
     exit $EXIT_SERVER_LOG_NOT_FOUND
   fi
 }
@@ -555,8 +555,7 @@ function sanity_check {
   # TODO: make check for root user in here.
 
   # make sure that there is a java binary installed in the PATH
-  which "$JAVA_BIN" &> /dev/null
-  if [[ $? != 0 ]]; then
+  if which "$JAVA_BIN" &> /dev/null; then
    warn "The java binary is not found."
    warn "Please install the necessary package(s) or specify the JAVA_BIN configuration option."
    warn ""
@@ -739,11 +738,9 @@ function get_server_download_uri () {
 # if something fails, it prints an error message and exits
 function backup_old_server () {
   # back up the old minecraft server (just in case)
-  mv "$MINECRAFT_SERVER_PATH" "${MINECRAFT_SERVER_PATH}.old"
-
-  if [[ "$?" != "0" ]]; then
-    echo "Failed backing up the old minecraft server!"
-    echo ""
+  if mv "$MINECRAFT_SERVER_PATH" "${MINECRAFT_SERVER_PATH}.old"; then
+    warn "Failed backing up the old minecraft server!"
+    warn ""
     exit $EXIT_CANNOT_BACKUP_OLD_MINECRAFT_SERVER
   fi
 }
@@ -763,10 +760,8 @@ function update_minecraft_server () {
   backup_old_server
   download_minecraft_server
 
-  if ! check_is_running; then
-    # server is not running, so just return
-    return
-  fi
+  # if the server isn't running, then return.
+  check_is_running || return
 
   read -p "Would you like to restart Minecraft Server? [Y/n]: " INPUT
   if [[ -z "$INPUT" || "$INPUT" == 'y' ]]; then
@@ -785,10 +780,8 @@ function update_minecraft_server () {
 # create the backup directory
 # if it exists, this effectively does nothing.
 function create_backup_directory () {
-  mkdir -p "$CURRENT_BACKUP_PATH"
-
-  if [[ $? != 0 ]]; then
-    #an error occurred
+  if mkdir -p "$CURRENT_BACKUP_PATH"; then
+    # an error occurred
     warn "An error occurred when creating the backup directory."
     exit $EXIT_CANNOT_CREATE_BACKUP_DIR
   fi
@@ -829,18 +822,15 @@ function do_backup () {
   fi
 
   # copy the current world directory into 'world' directory in current backup
-  cp -R "$WORLD_DATA_DIR" "$CURRENT_BACKUP_PATH/world"
-
-  if [[ $? != 0 ]]; then
-    #an error occurred
+  
+  if cp -R "$WORLD_DATA_DIR" "$CURRENT_BACKUP_PATH/world"; then
+    # an error occurred
     warn "An error occurred when copying the world data."
     exit $EXIT_CANNOT_BACKUP_WORLD_DATA
   fi
 
-  cp -R "${MINECRAFT_SERVER_DIR_PATH}/"*.{txt,properties} "$CURRENT_BACKUP_PATH/"
-
-  if [[ $? != 0 ]]; then
-    #an error occurred
+  if cp -R "${MINECRAFT_SERVER_DIR_PATH}/"*.{txt,properties} "$CURRENT_BACKUP_PATH/"; then
+    # an error occurred
     warn "An error occurred when copying the configuration information"
     exit $EXIT_CANNOT_BACKUP_CONFIGS
   fi
@@ -905,10 +895,8 @@ function create_symlink () {
   # then we symlink the current backup to "latest" in backups directory
   if [[ -L "$LATEST_BACKUP_PATH" ]]; then
     # if the symlink already exists, delete it before creating it.
-    rm "$LATEST_BACKUP_PATH"
-
-    if [[ $? != 0 ]]; then
-      #an error occurred
+    if rm "$LATEST_BACKUP_PATH"; then
+      # an error occurred
       warn "An error occurred when deleting the old symlink."
       exit $EXIT_FAILED_TO_DELETE_SYMLINK
     fi
@@ -919,10 +907,8 @@ function create_symlink () {
   # backup directory without issue.
   local NEW_BACKUP=$(basename "$CURRENT_BACKUP_PATH")
 
-  ln -s "$NEW_BACKUP" "$LATEST_BACKUP_PATH"
-
-  if [[ $? != 0 ]]; then
-    #an error occurred
+  if ln -s "$NEW_BACKUP" "$LATEST_BACKUP_PATH"; then
+    # an error occurred
     warn "An error occurred when creating the symlink."
     exit $EXIT_ERORR_CREATING_SYMLINK
   fi
