better error message when server not found

diff --git a/libexec/mcwrapper b/libexec/mcwrapper
--- a/libexec/mcwrapper
+++ b/libexec/mcwrapper
@@ -516,7 +516,14 @@ function sanity_check {
   # check to make sure that things that need to exist exist.
   if [[ ! -e "$MINECRAFT_SERVER_PATH" ]]; then
     # the minecraft server path does not exist.
-    echo "Minecraft server not found! (MINECRAFT_SERVER_PATH=$MINECRAFT_SERVER_PATH)" >&2
+    echo "Minecraft server not found!" >&2
+    
+    if [[ -z "$MINECRAFT_SERVER_PATH" ]]; then
+      echo "Default location: ./${MINECRAFT_SERVER_NAME}" >&2
+      echo "Or set MINECRAFT_SERVER_NAME" >&2
+    else
+      echo "(MINECRAFT_SERVER_PATH=$MINECRAFT_SERVER_PATH)" >&2
+    fi
     echo "" >&2
     exit $EXIT_MINECRAFT_SERVER_NOT_FOUND
   fi
