dont' check for function declaration
that was a bad feature idea on my part... you can re-declare any
functions in mcwrapper.conf and they'll override.

diff --git a/libexec/mcwrapper b/libexec/mcwrapper
--- a/libexec/mcwrapper
+++ b/libexec/mcwrapper
@@ -409,25 +409,22 @@ function read_pid {
 
 # this function can be overridden by defining it in mcwrapper.conf
 # the interface of the function is that it should return 0 if it's running or non-zero if it's not
+function check_is_running {
+  local PID=`read_pid`
 
-if ! type check_is_running &> /dev/null; then
-  function check_is_running {
-    local PID=`read_pid`
+  # if read_pid returned a non-zero status, then we're not running
+  if [[ $? != $EXIT_SUCCESS ]]; then
+    return $EXIT_SERVER_NOT_RUNNING
+  fi
 
-    # if read_pid returned a non-zero status, then we're not running
-    if [[ $? != $EXIT_SUCCESS ]]; then
-      return $EXIT_SERVER_NOT_RUNNING
-    fi
+  # check to see if we have a wrapper currently running
+  # send a 0 signal to process to see if it's running.
+  if ! kill -0 "$PID" &> /dev/null; then
+    return $EXIT_SERVER_NOT_RUNNING
+  fi
 
-    # check to see if we have a wrapper currently running
-    # send a 0 signal to process to see if it's running.
-    if ! kill -0 "$PID" &> /dev/null; then
-      return $EXIT_SERVER_NOT_RUNNING
-    fi
-
-    return $EXIT_SUCCESS
-  }
-fi
+  return $EXIT_SUCCESS
+}
 
 # ensure that the FIFO exists
 function set_up_pipe {
@@ -492,6 +489,8 @@ function start_minecraft {
   fi
 }
 
+# can be overridden
+# start minecraft in the background
 function start_minecraft_in_background {
   read_command | $MINECRAFT_SERVER_CMD &> /dev/null &
 }
