made function build default server command
this is to make it easier to override this functionality (especially for
docker integration)

diff --git a/libexec/mcwrapper b/libexec/mcwrapper
--- a/libexec/mcwrapper
+++ b/libexec/mcwrapper
@@ -293,7 +293,7 @@ function process_config {
   # this may be overridden in the config, so if it's set already, don't set it.
   if [[ -z "$MINECRAFT_SERVER_CMD" ]]; then
     # command for starting minecraft_server.jar
-    MINECRAFT_SERVER_CMD="$JAVA_BIN -Xmx${MX_SIZE} -Xms${MS_SIZE} -jar "$MINECRAFT_SERVER_PATH" nogui"
+    MINECRAFT_SERVER_CMD=$( default_minecraft_server_cmd "$JAVA_BIN" "$MINECRAFT_SERVER_PATH" )
   fi
 
   # the path to the server.properties file
@@ -463,6 +463,13 @@ function remove_pipe {
   fi
 }
 
+function default_minecraft_server_cmd {
+  local JAVA_BIN=$1
+  local MINECRAFT_SERVER_PATH=$2
+
+  echo "$JAVA_BIN" -Xmx${MX_SIZE} -Xms${MS_SIZE} -jar "$MINECRAFT_SERVER_PATH" nogui
+}
+
 # write the PID file and start'er up!
 # don't start if we're already running.
 # if FOREGROUND is defined, then start in foreground
@@ -475,19 +482,15 @@ function start_minecraft {
   # need to go to the directory to make sure that the Minecraft server puts the files in the right place (it puts them in the CWD)
   pushd $MINECRAFT_SERVER_DIR_PATH &> /dev/null
 
-  if [[ -z "$FOREGROUND" ]]; then
-    set_up_pipe
-    create_pid $(start_minecraft_in_background)
+  set_up_pipe
+  create_pid $(start_minecraft_in_background)
 
-    # sleep for one second to make sure that the process actually started properly.
-    sleep 1
+  # sleep for one second to make sure that the process actually started properly.
+  sleep 1
 
-    # verify that minecraft server actually started.
-    check_is_running \
-      || die "Could not start Minecraft Server." $EXIT_SERVER_CANNOT_START
-  else
-    start_minecraft_in_foreground
-  fi
+  # verify that minecraft server actually started.
+  check_is_running \
+    || die "Could not start Minecraft Server." $EXIT_SERVER_CANNOT_START
 }
 
 # can be overridden
